[package]
name = "virtual-gamepad"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"

[target.'cfg(target_os = "linux")'.dependencies]
evdev = { git = "https://github.com/Yamakaky/evdev", branch = "fixes" }

[target.windows.dependencies]
vigem-client = "0.1"
