[package]
name = "virtual-gamepad"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"

[target.'cfg(target_os = "linux")'.dependencies]
evdev = { version = "0.11", path = "../evdev" }

[target.windows.dependencies]
vigem-client = "0.1"
